version: "3.9"
services:
  kafka:
    image: kafka-example/kafka
    build:
      dockerfile: kafka.Dockerfile
      context: .
    links:
      - zookeeper
    volumes:
      - $PWD/kafka_2.13-3.2.1/config/server.properties:/home/kafka/kafka/config/server.properties
    ports:
      - "127.0.0.1:9092:9092"
  zookeeper:
    image: kafka-example/zookeeper
    build:
      dockerfile: zookeeper.Dockerfile
      context: .
    expose:
      - "2181"
